<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="shilpatailor.c.googlers.com" failures="3" tests="17" name="Regression" time="16.366" errors="0" timestamp="2024-08-31T12:10:07 UTC">
  <testcase classname="test.com.GoogleTest" name="pageTitle" time="0.012">
    <failure type="java.lang.AssertionError" message="title not match expected [Google1] but found [Google]">
      <![CDATA[java.lang.AssertionError: title not match expected [Google1] but found [Google]
at test.com.GoogleTest.pageTitle(GoogleTest.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- pageTitle -->
  <testcase classname="test.com.GoogleTest" name="googleLogoDisplayed" time="0.031"/>
  <testcase classname="test.com.GoogleTest" name="gmailLinkDisplayed" time="0.03"/>
  <testcase classname="test.com.GoogleTest" name="test1" time="0.001"/>
  <testcase classname="test.com.GoogleTest" name="test2" time="0.001"/>
  <testcase classname="test.com.BasicsTestNGTest" name="googleSearch" time="0.001"/>
  <testcase classname="test.com.BasicsTestNGTest" name="googleTitleTest" time="0.001"/>
  <testcase classname="test.com.ExceptionTimeoutTest" name="infintLoopTest" time="1.001">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method test.com.ExceptionTimeoutTest.infintLoopTest() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method test.com.ExceptionTimeoutTest.infintLoopTest() didn't finish within the time-out 1000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- infintLoopTest -->
  <testcase classname="test.com.ExceptionTimeoutTest" name="test1" time="0.0"/>
  <testcase classname="test.com.InvocationCountTest" name="sum" time="0.0"/>
  <testcase classname="test.com.InvocationCountTest" name="sum" time="0.001"/>
  <testcase classname="test.com.InvocationCountTest" name="sum" time="0.001"/>
  <testcase classname="test.com.InvocationCountTest" name="sum" time="0.0"/>
  <testcase classname="test.com.InvocationCountTest" name="sum" time="0.0"/>
  <testcase classname="test.com.TestNGFeature" name="loginPage" time="0.0">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at test.com.TestNGFeature.loginPage(TestNGFeature.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- loginPage -->
  <testcase classname="test.com.TestNGFeature" name="homePage" time="0.0">
    <skipped/>
  </testcase> <!-- homePage -->
  <testcase classname="test.com.TestNGFeature" name="searchPage" time="0.0">
    <skipped/>
  </testcase> <!-- searchPage -->
</testsuite> <!-- Regression -->
